version: "3.8"
services:
  backend:
    build: "./backend"
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
  frontend:
    build: "./frontend"
    volumes:
      - /app/node_modules
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
